config/routes.rb
Myapp::Application.routes.draw do
  resources :followings

  resources :responses

  resources :contact_lists

  resources :this_or_thats

  resources :users

  get "home/index"

  get "api/register" => 'api#register'

root to: 'home#index'

end

app/models/contact_list.rb
class ContactList < ActiveRecord::Base
end

app/controllers/contact_lists_controller.rb
class ContactListsController < ApplicationController
  before_action :set_contact_list, only: [:show, :edit, :update, :destroy]

  # GET /contact_lists
  # GET /contact_lists.json
  def index
    @contact_lists = ContactList.all
  end

  # GET /contact_lists/1
  # GET /contact_lists/1.json
  def show
  end

  # GET /contact_lists/new
  def new
    @contact_list = ContactList.new
  end

  # GET /contact_lists/1/edit
  def edit
  end

  # POST /contact_lists
  # POST /contact_lists.json
  def create
    @contact_list = ContactList.new(contact_list_params)

    respond_to do |format|
      if @contact_list.save
        format.html { redirect_to @contact_list, notice: 'Contact list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_lists/1
  # PATCH/PUT /contact_lists/1.json
  def update
    respond_to do |format|
      if @contact_list.update(contact_list_params)
        format.html { redirect_to @contact_list, notice: 'Contact list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_lists/1
  # DELETE /contact_lists/1.json
  def destroy
    @contact_list.destroy
    respond_to do |format|
      format.html { redirect_to contact_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_list
      @contact_list = ContactList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_list_params
      params.require(:contact_list).permit(:user_id, :contact_list)
    end
end

app/helpers/contact_lists_helper.rb
module ContactListsHelper
end

app/views/contact_lists/_form.html.erb
<%= form_for(@contact_list) do |f| %>
  <% if @contact_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_list.errors.count, "error") %> prohibited this contact_list from being saved:</h2>

      <ul>
      <% @contact_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contact_list %><br>
    <%= f.text_field :contact_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_lists/edit.html.erb
<h1>Editing contact_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_list %> |
<%= link_to 'Back', contact_lists_path %>

app/views/contact_lists/index.html.erb
<h1>Listing contact_lists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contact list</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_lists.each do |contact_list| %>
      <tr>
        <td><%= contact_list.user_id %></td>
        <td><%= contact_list.contact_list %></td>
        <td><%= link_to 'Show', contact_list %></td>
        <td><%= link_to 'Edit', edit_contact_list_path(contact_list) %></td>
        <td><%= link_to 'Destroy', contact_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact list', new_contact_list_path %>

app/views/contact_lists/new.html.erb
<h1>New contact_list</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_lists_path %>

app/views/contact_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contact_list.user_id %>
</p>

<p>
  <strong>Contact list:</strong>
  <%= @contact_list.contact_list %>
</p>

<%= link_to 'Edit', edit_contact_list_path(@contact_list) %> |
<%= link_to 'Back', contact_lists_path %>