config/routes.rb
Myapp::Application.routes.draw do
  resources :followings

  resources :responses

  resources :contact_lists

  resources :this_or_thats

  resources :users

  get "home/index"

  get "api/register" => 'api#register'

root to: 'home#index'

end

app/models/this_or_that.rb
class ThisOrThat < ActiveRecord::Base
end

app/controllers/this_or_thats_controller.rb
class ThisOrThatsController < ApplicationController
  before_action :set_this_or_that, only: [:show, :edit, :update, :destroy]

  # GET /this_or_thats
  # GET /this_or_thats.json
  def index
    @this_or_thats = ThisOrThat.all
  end

  # GET /this_or_thats/1
  # GET /this_or_thats/1.json
  def show
  end

  # GET /this_or_thats/new
  def new
    @this_or_that = ThisOrThat.new
  end

  # GET /this_or_thats/1/edit
  def edit
  end

  # POST /this_or_thats
  # POST /this_or_thats.json
  def create
    @this_or_that = ThisOrThat.new(this_or_that_params)

    respond_to do |format|
      if @this_or_that.save
        format.html { redirect_to @this_or_that, notice: 'This or that was successfully created.' }
        format.json { render action: 'show', status: :created, location: @this_or_that }
      else
        format.html { render action: 'new' }
        format.json { render json: @this_or_that.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /this_or_thats/1
  # PATCH/PUT /this_or_thats/1.json
  def update
    respond_to do |format|
      if @this_or_that.update(this_or_that_params)
        format.html { redirect_to @this_or_that, notice: 'This or that was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @this_or_that.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /this_or_thats/1
  # DELETE /this_or_thats/1.json
  def destroy
    @this_or_that.destroy
    respond_to do |format|
      format.html { redirect_to this_or_thats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_this_or_that
      @this_or_that = ThisOrThat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def this_or_that_params
      params.require(:this_or_that).permit(:image1, :image2, :description, :comment, :is_private, :user_id, :pants_brand, :shirt_brand, :shoes_brand, :hat_brand, :jacket_brand)
    end
end

app/helpers/this_or_thats_helper.rb
module ThisOrThatsHelper
end

app/views/this_or_thats/_form.html.erb
<%= form_for(@this_or_that) do |f| %>
  <% if @this_or_that.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@this_or_that.errors.count, "error") %> prohibited this this_or_that from being saved:</h2>

      <ul>
      <% @this_or_that.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image1 %><br>
    <%= f.text_field :image1 %>
  </div>
  <div class="field">
    <%= f.label :image2 %><br>
    <%= f.text_field :image2 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :is_private %><br>
    <%= f.check_box :is_private %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :pants_brand %><br>
    <%= f.text_field :pants_brand %>
  </div>
  <div class="field">
    <%= f.label :shirt_brand %><br>
    <%= f.text_field :shirt_brand %>
  </div>
  <div class="field">
    <%= f.label :shoes_brand %><br>
    <%= f.text_field :shoes_brand %>
  </div>
  <div class="field">
    <%= f.label :hat_brand %><br>
    <%= f.text_field :hat_brand %>
  </div>
  <div class="field">
    <%= f.label :jacket_brand %><br>
    <%= f.text_field :jacket_brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/this_or_thats/edit.html.erb
<h1>Editing this_or_that</h1>

<%= render 'form' %>

<%= link_to 'Show', @this_or_that %> |
<%= link_to 'Back', this_or_thats_path %>

app/views/this_or_thats/index.html.erb
<h1>Listing this_or_thats</h1>

<table>
  <thead>
    <tr>
      <th>Image1</th>
      <th>Image2</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Is private</th>
      <th>User</th>
      <th>Pants brand</th>
      <th>Shirt brand</th>
      <th>Shoes brand</th>
      <th>Hat brand</th>
      <th>Jacket brand</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @this_or_thats.each do |this_or_that| %>
      <tr>
        <td><%= this_or_that.image1 %></td>
        <td><%= this_or_that.image2 %></td>
        <td><%= this_or_that.description %></td>
        <td><%= this_or_that.comment %></td>
        <td><%= this_or_that.is_private %></td>
        <td><%= this_or_that.user_id %></td>
        <td><%= this_or_that.pants_brand %></td>
        <td><%= this_or_that.shirt_brand %></td>
        <td><%= this_or_that.shoes_brand %></td>
        <td><%= this_or_that.hat_brand %></td>
        <td><%= this_or_that.jacket_brand %></td>
        <td><%= link_to 'Show', this_or_that %></td>
        <td><%= link_to 'Edit', edit_this_or_that_path(this_or_that) %></td>
        <td><%= link_to 'Destroy', this_or_that, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New This or that', new_this_or_that_path %>

app/views/this_or_thats/new.html.erb
<h1>New this_or_that</h1>

<%= render 'form' %>

<%= link_to 'Back', this_or_thats_path %>

app/views/this_or_thats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image1:</strong>
  <%= @this_or_that.image1 %>
</p>

<p>
  <strong>Image2:</strong>
  <%= @this_or_that.image2 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @this_or_that.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @this_or_that.comment %>
</p>

<p>
  <strong>Is private:</strong>
  <%= @this_or_that.is_private %>
</p>

<p>
  <strong>User:</strong>
  <%= @this_or_that.user_id %>
</p>

<p>
  <strong>Pants brand:</strong>
  <%= @this_or_that.pants_brand %>
</p>

<p>
  <strong>Shirt brand:</strong>
  <%= @this_or_that.shirt_brand %>
</p>

<p>
  <strong>Shoes brand:</strong>
  <%= @this_or_that.shoes_brand %>
</p>

<p>
  <strong>Hat brand:</strong>
  <%= @this_or_that.hat_brand %>
</p>

<p>
  <strong>Jacket brand:</strong>
  <%= @this_or_that.jacket_brand %>
</p>

<%= link_to 'Edit', edit_this_or_that_path(@this_or_that) %> |
<%= link_to 'Back', this_or_thats_path %>